# Archivo en la raíz del proyecto
sonar.projectKey=e97788df0148a761964c1dda0eb7333d9d112a96
sonar.organization=adrianawzw
sonar.host.url=https://sonarcloud.io
# Ruta estándar donde Maven guarda el reporte de JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml